using System.Collections.Generic;

namespace OkkhorLib
{
    internal class Pattern
    {
        public string Find { get; private set; }
        private string Replace { get; set; }
        private string ConsonantReplace { get; set; }

        public string GetReplacement(bool isPrefixConsonant) =>
            isPrefixConsonant ? ConsonantReplace : Replace;

        private static Pattern Simple(string find, string replace) =>
            new Pattern
            {
                Find = find,
                Replace = replace,
                ConsonantReplace = replace
            };

        private static Pattern New(string find, string replace, string consonantReplace) =>
            new Pattern
            {
                Find = find,
                Replace = replace,
                ConsonantReplace = consonantReplace
            };

        public static List<Pattern> PHONETIC_PATTERNS = new List<Pattern>
        {
            New("o", "অ", ""),
            New("a", "আ", "া"),
            New("i", "ই", "ি"),
            New("I", "ঈ", "ী"),
            New("ee", "ঈ", "ী"),
            New("u", "উ", "ু"),
            New("oo", "উ", "ু"),
            New("U", "ঊ", "ূ"),
            New("rri", "ঋ", "ৃ"),
            New("e", "এ", "ে"),
            New("OI", "ঐ", "ৈ"),
            New("O", "ও", "ো"),
            New("OU", "ঔ", "ৌ"),
            New("k", "ক", "্ক"),
            New("kh", "খ", "্খ"),
            New("g", "গ", "্গ"),
            New("G", "গ", "্গ"),
            New("gh", "ঘ", "্ঘ"),
            New("Gh", "ঘ", "্ঘ"),
            New("Ng", "ঙ", "্ঙ"),
            Simple("c", "চ"),
            Simple("cc", "চ্চ"),
            Simple("cch", "চ্ছ"),
            Simple("shc", "শ্চ"),
            Simple("Sc", "শ্চ"),
            Simple("shch", "শ্ছ"),
            Simple("Sch", "শ্ছ"),
            New("ch", "ছ", "্ছ"),
            New("j", "জ", "্জ"),
            New("J", "জ", "্জ"),
            New("jh", "ঝ", "্ঝ"),
            New("Jh", "ঝ", "্ঝ"),
            New("NG", "ঞ", "্ঞ"),
            New("T", "ট", "্ট"),
            New("Th", "ঠ", "্ঠ"),
            New("D", "ড", "্ড"),
            New("Dh", "ঢ", "্ঢ"),
            New("N", "ণ", "্ণ"),
            New("t", "ত", "্ত"),
            New("th", "থ", "্থ"),
            New("d", "দ", "্দ"),
            New("dh", "ধ", "্ধ"),
            New("n", "ন", "্ন"),
            New("p", "প", "্প"),
            New("ph", "ফ", "্ফ"),
            New("f", "ফ", "্ফ"),
            New("b", "ব", "্ব"),
            New("bh", "ভ", "্ভ"),
            New("v", "ভ", "্ভ"),
            New("m", "ম", "্ম"),
            Simple("z", "য"),
            Simple("Z", "্য"),
            Simple("aZ", "অ্যা"),
            New("y", "য়", "্য"),
            New("r", "র", "্র"),
            New("rZ", "র‍্য", "্র্য"),
            New("ry", "র‍্য", "্র্য"),
            New("rr", "রর", "্রর"),
            New("rrZ", "রর‍্য", "্রর‍্য"),
            New("rry", "রর‍্য", "্রর‍্য"),
            Simple("ngl", "ংল"),
            New("l", "ল", "্ল"),
            New("sh", "শ", "শ"),
            New("S", "শ", "শ"),
            New("Sh", "ষ", "্ষ"),
            New("s", "স", "্স"),
            New("h", "হ", "্হ"),
            New("w", "ও", "্ব"),
            New("kx", "ক্ষ", "্ক্ষ"),
            New("kkh", "ক্ষ", "্ক্ষ"),
            Simple("ng", "ং"),
            Simple("ngo", "ঙ্গ"),
            Simple("nga", "ঙ্গা"),
            Simple("ngi", "ঙ্গি"),
            Simple("ngI", "ঙ্গী"),
            Simple("ngu", "ঙ্গু"),
            Simple("ngU", "ঙ্গূ"),
            Simple("nge", "ঙ্গে"),
            Simple("ngO", "ঙ্গো"),
            Simple("ngOU", "ঙ্গৌ"),
            Simple("ngOI", "ঙ্গৈ"),
            Simple("NGch", "ঞ্ছ"),
            Simple("ia", "ইয়া"),
            Simple("wa", "ওয়া"),
            Simple("q", "ক"),
            Simple("R", "ড়"),
            Simple("Rh", "ঢ়"),
            Simple("Y", "য়"),
            Simple("x", "ক্স"),
            Simple("gg", "জ্ঞ"),
            Simple("GG", "জ্ঞ"),
            Simple("Gg", "জ্ঞ"),
            Simple("gG", "জ্ঞ"),
            Simple("lkh", "লখ"),
            Simple("mpl", "মপ্ল"),
            Simple("lgh", "লঘ"),
            Simple("lph", "লফ"),
            Simple("nkh", "ঙ্খ"),
            Simple("NGc", "ঞ্চ"),
            Simple("nch", "ঞ্ছ"),
            Simple("njh", "ঞ্ঝ"),
            Simple("ngh", "ঙ্ঘ"),
            Simple("Ngx", "ঙ্ষ"),
            Simple("Ngg", "ঙ্গ"),
            Simple("Nggh", "ঙ্ঘ"),
            Simple("Ngr", "ঙর"),
            Simple("NGr", "ঞর"),
            Simple("ngr", "ংর"),
            Simple("nj", "ঞ্জ"),
            Simple("nk", "ঙ্ক"),
            Simple("nc", "ঞ্চ"),
            Simple("o`", ""),
            Simple("a`", "া"),
            Simple("i`", "ি"),
            Simple("I`", "ী"),
            Simple("ee`", "ী"),
            Simple("u`", "ু"),
            Simple("oo`", "ু"),
            Simple("U`", "ূ"),
            Simple("rri`", "ৃ"),
            Simple("e`", "ে"),
            Simple("OI`", "ৈ"),
            Simple("O`", "ো"),
            Simple("OU`", "ৌ"),
            Simple("t``", "ৎ"),
            Simple(":`", ":"),
            Simple(":", "ঃ"),
            Simple("^`", "^"),
            Simple("^", "ঁ"),
            Simple(",,", "্‌"),
            Simple(",", ","),
            Simple("$", "৳"),
            Simple("`", ""),
            Simple("0", "০"),
            Simple("1", "১"),
            Simple("2", "২"),
            Simple("3", "৩"),
            Simple("4", "৪"),
            Simple("5", "৫"),
            Simple("6", "৬"),
            Simple("7", "৭"),
            Simple("8", "৮"),
            Simple("9", "৯"),
            Simple("...", "..."),
            Simple(".`", "."),
            Simple("..", "।।"),
            Simple(".", "।"),
        };
    }
}
